### ISSUE TITLE
Icon has.gone bluewallet

### ISSUE THREAD

**Issue by NatoshiSakamot** [boltcard/boltcard-wallet#12]
When I first downloaded wallet (Android), the custom Boltcard wallet icon displayed.  It has now reverted to a bluewallet icon?  

![Screenshot_20230315-131526](https://user-images.githubusercontent.com/104597290/225321105-77cda635-f1ff-4ec3-a743-81073a7eccd1.jpg)

**Comment by robertclarkson** [comment]
circular icons added
