### ISSUE TITLE
Wording on wallet is distracting

### ISSUE THREAD

**Issue by NatoshiSakamot** [boltcard/boltcard-wallet#13]
![Screenshot_20230315-131351](https://user-images.githubusercontent.com/104597290/225322909-c3eb2e45-67c0-49ac-8222-a34f0e820649.jpg)

Wording refers to tapping on 'Manage Funds', no such button or menu item I can see.  Clicking receive seems fine.

Please provide:

* OnePlus 7T Android 11 Oxygen OS 11 0.9.1.HD65BA
* BoltCardWallet app version 0.1.2 build 1678747118

**Comment by robertclarkson** [comment]
fixed in commit [08db90c9480fb77ae0efa2ecc0a2be1fedee2b76](https://github.com/boltcard/boltcard-wallet/commit/08db90c9480fb77ae0efa2ecc0a2be1fedee2b76)
