### ISSUE TITLE
Consider removing the "LApp Browser" button

### ISSUE THREAD

**Issue by PeterRounce** [boltcard/boltcard-wallet#15]
# Feature Request

On the bolt card wallet screen, the "LApp Browser" button looks like it is not needed.
All other functions on the screen have a purpose (Bolt Card balance, details & transactions).

On my phone it brings up a browser on a default search page (i.e. not useful).

On BlueWallet, the button only exists for Lightning wallets and not for Bitcoin wallets.

I suggest we remove the button as it will make the screen simpler and give a cleaner design.

![app-1](https://user-images.githubusercontent.com/99006127/225329392-78be01b5-3a81-44ae-83e1-9503f93e9937.jpg)

**Comment by robertclarkson** [comment]
removed
